/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Contact = IDL.Record({
  'id' : IDL.Nat,
  'contactInfo' : IDL.Text,
  'contactCategory' : IDL.Variant({
    'wholesaler' : IDL.Null,
    'retailer' : IDL.Null,
  }),
  'contactType' : IDL.Variant({ 'purchaser' : IDL.Null, 'billTo' : IDL.Null }),
  'name' : IDL.Text,
});
export const Time = IDL.Int;
export const PriceOverrideRequest = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  }),
  'referenceId' : IDL.Opt(IDL.Nat),
  'sellingPrice' : IDL.Float64,
  'costPrice' : IDL.Float64,
  'requestType' : IDL.Variant({ 'estimate' : IDL.Null, 'purchase' : IDL.Null }),
  'requestedAt' : Time,
  'requestedBy' : IDL.Principal,
});
export const InventoryItem = IDL.Record({
  'lastUpdated' : Time,
  'productId' : IDL.Nat,
  'quantity' : IDL.Int,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const CompanyBranding = IDL.Record({
  'logo' : IDL.Opt(ExternalBlob),
  'name' : IDL.Text,
  'address' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Purchase = IDL.Record({
  'id' : IDL.Nat,
  'hasOverride' : IDL.Bool,
  'purchaseDate' : Time,
  'item' : IDL.Text,
  'sellingPrice' : IDL.Float64,
  'notes' : IDL.Text,
  'purchaser' : IDL.Text,
  'quantity' : IDL.Int,
  'costPrice' : IDL.Float64,
  'profitPercentage' : IDL.Float64,
});
export const EstimateItem = IDL.Record({
  'rate' : IDL.Float64,
  'description' : IDL.Text,
  'quantity' : IDL.Float64,
  'amount' : IDL.Float64,
});
export const Estimate = IDL.Record({
  'id' : IDL.Nat,
  'customerName' : IDL.Text,
  'lineItems' : IDL.Vec(EstimateItem),
  'netAmount' : IDL.Float64,
  'createdAt' : Time,
  'paymentReceivedTimestamp' : IDL.Opt(Time),
  'isPaid' : IDL.Bool,
  'customerAddress' : IDL.Text,
  'totalAmount' : IDL.Float64,
  'paidAmount' : IDL.Float64,
  'pendingAmount' : IDL.Float64,
});
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'stockQuantity' : IDL.Int,
  'name' : IDL.Text,
  'isActive' : IDL.Bool,
  'category' : IDL.Text,
  'price' : IDL.Float64,
});
export const BackupData = IDL.Record({
  'contacts' : IDL.Vec(IDL.Tuple(IDL.Nat, Contact)),
  'priceOverrideRequests' : IDL.Vec(IDL.Tuple(IDL.Nat, PriceOverrideRequest)),
  'inventory' : IDL.Vec(IDL.Tuple(IDL.Nat, InventoryItem)),
  'companyBranding' : IDL.Opt(CompanyBranding),
  'userProfiles' : IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile)),
  'purchases' : IDL.Vec(IDL.Tuple(IDL.Nat, Purchase)),
  'estimates' : IDL.Vec(IDL.Tuple(IDL.Nat, Estimate)),
  'products' : IDL.Vec(IDL.Tuple(IDL.Nat, Product)),
});
export const ProfitAndLoss = IDL.Record({
  'startTime' : Time,
  'endTime' : Time,
  'totalIncome' : IDL.Float64,
  'totalExpense' : IDL.Float64,
  'netProfit' : IDL.Float64,
});
export const TransactionType = IDL.Variant({
  'estimate' : IDL.Null,
  'purchase' : IDL.Null,
});
export const Transaction = IDL.Record({
  'id' : IDL.Nat,
  'transactionType' : TransactionType,
  'date' : Time,
  'itemOrCustomer' : IDL.Text,
  'quantity' : IDL.Int,
  'price' : IDL.Float64,
});
export const ApprovalStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const UserApprovalInfo = IDL.Record({
  'status' : ApprovalStatus,
  'principal' : IDL.Principal,
});
export const EstimatePrintData = IDL.Record({
  'companyBranding' : IDL.Opt(CompanyBranding),
  'estimate' : Estimate,
  'previousPendingAmount' : IDL.Float64,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addContact' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Variant({ 'purchaser' : IDL.Null, 'billTo' : IDL.Null }),
        IDL.Variant({ 'wholesaler' : IDL.Null, 'retailer' : IDL.Null }),
      ],
      [IDL.Nat],
      [],
    ),
  'addProduct' : IDL.Func([IDL.Text, IDL.Text, IDL.Float64], [IDL.Nat], []),
  'approvePriceOverride' : IDL.Func([IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'backupExport' : IDL.Func([], [BackupData], []),
  'backupImport' : IDL.Func([BackupData], [], []),
  'createEstimate' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(EstimateItem), IDL.Float64, IDL.Float64],
      [IDL.Nat],
      [],
    ),
  'createPurchase' : IDL.Func(
      [
        IDL.Text,
        IDL.Int,
        IDL.Float64,
        IDL.Float64,
        IDL.Text,
        IDL.Text,
        IDL.Bool,
      ],
      [IDL.Nat],
      [],
    ),
  'deleteContact' : IDL.Func([IDL.Nat], [], []),
  'deleteProduct' : IDL.Func([IDL.Nat], [], []),
  'deletePurchase' : IDL.Func([IDL.Nat], [], []),
  'generateProfitAndLossReport' : IDL.Func(
      [Time, Time],
      [ProfitAndLoss],
      ['query'],
    ),
  'getAllContacts' : IDL.Func([], [IDL.Vec(Contact)], ['query']),
  'getAllEstimates' : IDL.Func([], [IDL.Vec(Estimate)], ['query']),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getAllPurchases' : IDL.Func([], [IDL.Vec(Purchase)], ['query']),
  'getAllTransactions' : IDL.Func([], [IDL.Vec(Transaction)], []),
  'getBillToContacts' : IDL.Func([], [IDL.Vec(Contact)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCompanyBranding' : IDL.Func([], [IDL.Opt(CompanyBranding)], ['query']),
  'getPriceOverrideRequests' : IDL.Func(
      [],
      [IDL.Vec(PriceOverrideRequest)],
      ['query'],
    ),
  'getPurchaserContacts' : IDL.Func([], [IDL.Vec(Contact)], ['query']),
  'getReportTotals' : IDL.Func(
      [Time, Time],
      [IDL.Float64, IDL.Float64],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
  'isOpenAccess' : IDL.Func([], [IDL.Bool], ['query']),
  'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
  'markEstimateAsPaid' : IDL.Func([IDL.Nat], [], []),
  'printEstimate' : IDL.Func([IDL.Nat], [EstimatePrintData], ['query']),
  'recordEstimatePayment' : IDL.Func([IDL.Nat, IDL.Float64], [], []),
  'rejectPriceOverride' : IDL.Func([IDL.Nat], [], []),
  'requestApproval' : IDL.Func([], [], []),
  'requestPriceOverride' : IDL.Func(
      [
        IDL.Variant({ 'estimate' : IDL.Null, 'purchase' : IDL.Null }),
        IDL.Float64,
        IDL.Float64,
      ],
      [IDL.Nat],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchTransactions' : IDL.Func([IDL.Text], [IDL.Vec(Transaction)], []),
  'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
  'setCompanyBranding' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(ExternalBlob)],
      [],
      [],
    ),
  'toggleOpenAccess' : IDL.Func([IDL.Bool], [], []),
  'updateContact' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Variant({ 'purchaser' : IDL.Null, 'billTo' : IDL.Null }),
        IDL.Variant({ 'wholesaler' : IDL.Null, 'retailer' : IDL.Null }),
      ],
      [],
      [],
    ),
  'updateEstimate' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Vec(EstimateItem),
        IDL.Float64,
        IDL.Float64,
        IDL.Bool,
        IDL.Float64,
        IDL.Float64,
        IDL.Opt(Time),
      ],
      [],
      [],
    ),
  'updateProduct' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Float64],
      [],
      [],
    ),
  'updatePurchase' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Int,
        IDL.Float64,
        IDL.Float64,
        IDL.Text,
        IDL.Text,
        IDL.Bool,
      ],
      [],
      [],
    ),
  'updateStock' : IDL.Func([IDL.Nat, IDL.Int], [], []),
  'validatePricing' : IDL.Func(
      [IDL.Float64, IDL.Float64],
      [IDL.Bool],
      ['query'],
    ),
  'validateUser' : IDL.Func([], [IDL.Bool], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Contact = IDL.Record({
    'id' : IDL.Nat,
    'contactInfo' : IDL.Text,
    'contactCategory' : IDL.Variant({
      'wholesaler' : IDL.Null,
      'retailer' : IDL.Null,
    }),
    'contactType' : IDL.Variant({
      'purchaser' : IDL.Null,
      'billTo' : IDL.Null,
    }),
    'name' : IDL.Text,
  });
  const Time = IDL.Int;
  const PriceOverrideRequest = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Variant({
      'pending' : IDL.Null,
      'approved' : IDL.Null,
      'rejected' : IDL.Null,
    }),
    'referenceId' : IDL.Opt(IDL.Nat),
    'sellingPrice' : IDL.Float64,
    'costPrice' : IDL.Float64,
    'requestType' : IDL.Variant({
      'estimate' : IDL.Null,
      'purchase' : IDL.Null,
    }),
    'requestedAt' : Time,
    'requestedBy' : IDL.Principal,
  });
  const InventoryItem = IDL.Record({
    'lastUpdated' : Time,
    'productId' : IDL.Nat,
    'quantity' : IDL.Int,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const CompanyBranding = IDL.Record({
    'logo' : IDL.Opt(ExternalBlob),
    'name' : IDL.Text,
    'address' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Purchase = IDL.Record({
    'id' : IDL.Nat,
    'hasOverride' : IDL.Bool,
    'purchaseDate' : Time,
    'item' : IDL.Text,
    'sellingPrice' : IDL.Float64,
    'notes' : IDL.Text,
    'purchaser' : IDL.Text,
    'quantity' : IDL.Int,
    'costPrice' : IDL.Float64,
    'profitPercentage' : IDL.Float64,
  });
  const EstimateItem = IDL.Record({
    'rate' : IDL.Float64,
    'description' : IDL.Text,
    'quantity' : IDL.Float64,
    'amount' : IDL.Float64,
  });
  const Estimate = IDL.Record({
    'id' : IDL.Nat,
    'customerName' : IDL.Text,
    'lineItems' : IDL.Vec(EstimateItem),
    'netAmount' : IDL.Float64,
    'createdAt' : Time,
    'paymentReceivedTimestamp' : IDL.Opt(Time),
    'isPaid' : IDL.Bool,
    'customerAddress' : IDL.Text,
    'totalAmount' : IDL.Float64,
    'paidAmount' : IDL.Float64,
    'pendingAmount' : IDL.Float64,
  });
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'stockQuantity' : IDL.Int,
    'name' : IDL.Text,
    'isActive' : IDL.Bool,
    'category' : IDL.Text,
    'price' : IDL.Float64,
  });
  const BackupData = IDL.Record({
    'contacts' : IDL.Vec(IDL.Tuple(IDL.Nat, Contact)),
    'priceOverrideRequests' : IDL.Vec(IDL.Tuple(IDL.Nat, PriceOverrideRequest)),
    'inventory' : IDL.Vec(IDL.Tuple(IDL.Nat, InventoryItem)),
    'companyBranding' : IDL.Opt(CompanyBranding),
    'userProfiles' : IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile)),
    'purchases' : IDL.Vec(IDL.Tuple(IDL.Nat, Purchase)),
    'estimates' : IDL.Vec(IDL.Tuple(IDL.Nat, Estimate)),
    'products' : IDL.Vec(IDL.Tuple(IDL.Nat, Product)),
  });
  const ProfitAndLoss = IDL.Record({
    'startTime' : Time,
    'endTime' : Time,
    'totalIncome' : IDL.Float64,
    'totalExpense' : IDL.Float64,
    'netProfit' : IDL.Float64,
  });
  const TransactionType = IDL.Variant({
    'estimate' : IDL.Null,
    'purchase' : IDL.Null,
  });
  const Transaction = IDL.Record({
    'id' : IDL.Nat,
    'transactionType' : TransactionType,
    'date' : Time,
    'itemOrCustomer' : IDL.Text,
    'quantity' : IDL.Int,
    'price' : IDL.Float64,
  });
  const ApprovalStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const UserApprovalInfo = IDL.Record({
    'status' : ApprovalStatus,
    'principal' : IDL.Principal,
  });
  const EstimatePrintData = IDL.Record({
    'companyBranding' : IDL.Opt(CompanyBranding),
    'estimate' : Estimate,
    'previousPendingAmount' : IDL.Float64,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addContact' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Variant({ 'purchaser' : IDL.Null, 'billTo' : IDL.Null }),
          IDL.Variant({ 'wholesaler' : IDL.Null, 'retailer' : IDL.Null }),
        ],
        [IDL.Nat],
        [],
      ),
    'addProduct' : IDL.Func([IDL.Text, IDL.Text, IDL.Float64], [IDL.Nat], []),
    'approvePriceOverride' : IDL.Func([IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'backupExport' : IDL.Func([], [BackupData], []),
    'backupImport' : IDL.Func([BackupData], [], []),
    'createEstimate' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(EstimateItem), IDL.Float64, IDL.Float64],
        [IDL.Nat],
        [],
      ),
    'createPurchase' : IDL.Func(
        [
          IDL.Text,
          IDL.Int,
          IDL.Float64,
          IDL.Float64,
          IDL.Text,
          IDL.Text,
          IDL.Bool,
        ],
        [IDL.Nat],
        [],
      ),
    'deleteContact' : IDL.Func([IDL.Nat], [], []),
    'deleteProduct' : IDL.Func([IDL.Nat], [], []),
    'deletePurchase' : IDL.Func([IDL.Nat], [], []),
    'generateProfitAndLossReport' : IDL.Func(
        [Time, Time],
        [ProfitAndLoss],
        ['query'],
      ),
    'getAllContacts' : IDL.Func([], [IDL.Vec(Contact)], ['query']),
    'getAllEstimates' : IDL.Func([], [IDL.Vec(Estimate)], ['query']),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getAllPurchases' : IDL.Func([], [IDL.Vec(Purchase)], ['query']),
    'getAllTransactions' : IDL.Func([], [IDL.Vec(Transaction)], []),
    'getBillToContacts' : IDL.Func([], [IDL.Vec(Contact)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCompanyBranding' : IDL.Func([], [IDL.Opt(CompanyBranding)], ['query']),
    'getPriceOverrideRequests' : IDL.Func(
        [],
        [IDL.Vec(PriceOverrideRequest)],
        ['query'],
      ),
    'getPurchaserContacts' : IDL.Func([], [IDL.Vec(Contact)], ['query']),
    'getReportTotals' : IDL.Func(
        [Time, Time],
        [IDL.Float64, IDL.Float64],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
    'isOpenAccess' : IDL.Func([], [IDL.Bool], ['query']),
    'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
    'markEstimateAsPaid' : IDL.Func([IDL.Nat], [], []),
    'printEstimate' : IDL.Func([IDL.Nat], [EstimatePrintData], ['query']),
    'recordEstimatePayment' : IDL.Func([IDL.Nat, IDL.Float64], [], []),
    'rejectPriceOverride' : IDL.Func([IDL.Nat], [], []),
    'requestApproval' : IDL.Func([], [], []),
    'requestPriceOverride' : IDL.Func(
        [
          IDL.Variant({ 'estimate' : IDL.Null, 'purchase' : IDL.Null }),
          IDL.Float64,
          IDL.Float64,
        ],
        [IDL.Nat],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchTransactions' : IDL.Func([IDL.Text], [IDL.Vec(Transaction)], []),
    'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
    'setCompanyBranding' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(ExternalBlob)],
        [],
        [],
      ),
    'toggleOpenAccess' : IDL.Func([IDL.Bool], [], []),
    'updateContact' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Variant({ 'purchaser' : IDL.Null, 'billTo' : IDL.Null }),
          IDL.Variant({ 'wholesaler' : IDL.Null, 'retailer' : IDL.Null }),
        ],
        [],
        [],
      ),
    'updateEstimate' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Vec(EstimateItem),
          IDL.Float64,
          IDL.Float64,
          IDL.Bool,
          IDL.Float64,
          IDL.Float64,
          IDL.Opt(Time),
        ],
        [],
        [],
      ),
    'updateProduct' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Float64],
        [],
        [],
      ),
    'updatePurchase' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Int,
          IDL.Float64,
          IDL.Float64,
          IDL.Text,
          IDL.Text,
          IDL.Bool,
        ],
        [],
        [],
      ),
    'updateStock' : IDL.Func([IDL.Nat, IDL.Int], [], []),
    'validatePricing' : IDL.Func(
        [IDL.Float64, IDL.Float64],
        [IDL.Bool],
        ['query'],
      ),
    'validateUser' : IDL.Func([], [IDL.Bool], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };