/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ApprovalStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface BackupData {
  'contacts' : Array<[bigint, Contact]>,
  'priceOverrideRequests' : Array<[bigint, PriceOverrideRequest]>,
  'inventory' : Array<[bigint, InventoryItem]>,
  'companyBranding' : [] | [CompanyBranding],
  'userProfiles' : Array<[Principal, UserProfile]>,
  'purchases' : Array<[bigint, Purchase]>,
  'estimates' : Array<[bigint, Estimate]>,
  'products' : Array<[bigint, Product]>,
}
export interface CompanyBranding {
  'logo' : [] | [ExternalBlob],
  'name' : string,
  'address' : string,
}
export interface Contact {
  'id' : bigint,
  'contactInfo' : string,
  'contactCategory' : { 'wholesaler' : null } |
    { 'retailer' : null },
  'contactType' : { 'purchaser' : null } |
    { 'billTo' : null },
  'name' : string,
}
export interface Estimate {
  'id' : bigint,
  'customerName' : string,
  'lineItems' : Array<EstimateItem>,
  'netAmount' : number,
  'createdAt' : Time,
  'paymentReceivedTimestamp' : [] | [Time],
  'isPaid' : boolean,
  'customerAddress' : string,
  'totalAmount' : number,
  'paidAmount' : number,
  'pendingAmount' : number,
}
export interface EstimateItem {
  'rate' : number,
  'description' : string,
  'quantity' : number,
  'amount' : number,
}
export interface EstimatePrintData {
  'companyBranding' : [] | [CompanyBranding],
  'estimate' : Estimate,
  'previousPendingAmount' : number,
}
export type ExternalBlob = Uint8Array;
export interface InventoryItem {
  'lastUpdated' : Time,
  'productId' : bigint,
  'quantity' : bigint,
}
export interface PriceOverrideRequest {
  'id' : bigint,
  'status' : { 'pending' : null } |
    { 'approved' : null } |
    { 'rejected' : null },
  'referenceId' : [] | [bigint],
  'sellingPrice' : number,
  'costPrice' : number,
  'requestType' : { 'estimate' : null } |
    { 'purchase' : null },
  'requestedAt' : Time,
  'requestedBy' : Principal,
}
export interface Product {
  'id' : bigint,
  'stockQuantity' : bigint,
  'name' : string,
  'isActive' : boolean,
  'category' : string,
  'price' : number,
}
export interface ProfitAndLoss {
  'startTime' : Time,
  'endTime' : Time,
  'totalIncome' : number,
  'totalExpense' : number,
  'netProfit' : number,
}
export interface Purchase {
  'id' : bigint,
  'hasOverride' : boolean,
  'purchaseDate' : Time,
  'item' : string,
  'sellingPrice' : number,
  'notes' : string,
  'purchaser' : string,
  'quantity' : bigint,
  'costPrice' : number,
  'profitPercentage' : number,
}
export type Time = bigint;
export interface Transaction {
  'id' : bigint,
  'transactionType' : TransactionType,
  'date' : Time,
  'itemOrCustomer' : string,
  'quantity' : bigint,
  'price' : number,
}
export type TransactionType = { 'estimate' : null } |
  { 'purchase' : null };
export interface UserApprovalInfo {
  'status' : ApprovalStatus,
  'principal' : Principal,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addContact' : ActorMethod<
    [
      string,
      string,
      { 'purchaser' : null } |
        { 'billTo' : null },
      { 'wholesaler' : null } |
        { 'retailer' : null },
    ],
    bigint
  >,
  'addProduct' : ActorMethod<[string, string, number], bigint>,
  'approvePriceOverride' : ActorMethod<[bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'backupExport' : ActorMethod<[], BackupData>,
  'backupImport' : ActorMethod<[BackupData], undefined>,
  'createEstimate' : ActorMethod<
    [string, string, Array<EstimateItem>, number, number],
    bigint
  >,
  'createPurchase' : ActorMethod<
    [string, bigint, number, number, string, string, boolean],
    bigint
  >,
  'deleteContact' : ActorMethod<[bigint], undefined>,
  'deleteProduct' : ActorMethod<[bigint], undefined>,
  'deletePurchase' : ActorMethod<[bigint], undefined>,
  'generateProfitAndLossReport' : ActorMethod<[Time, Time], ProfitAndLoss>,
  'getAllContacts' : ActorMethod<[], Array<Contact>>,
  'getAllEstimates' : ActorMethod<[], Array<Estimate>>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getAllPurchases' : ActorMethod<[], Array<Purchase>>,
  'getAllTransactions' : ActorMethod<[], Array<Transaction>>,
  'getBillToContacts' : ActorMethod<[], Array<Contact>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCompanyBranding' : ActorMethod<[], [] | [CompanyBranding]>,
  'getPriceOverrideRequests' : ActorMethod<[], Array<PriceOverrideRequest>>,
  'getPurchaserContacts' : ActorMethod<[], Array<Contact>>,
  'getReportTotals' : ActorMethod<[Time, Time], [number, number]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCallerApproved' : ActorMethod<[], boolean>,
  'listApprovals' : ActorMethod<[], Array<UserApprovalInfo>>,
  'markEstimateAsPaid' : ActorMethod<[bigint], undefined>,
  'printEstimate' : ActorMethod<[bigint], EstimatePrintData>,
  'recordEstimatePayment' : ActorMethod<[bigint, number], undefined>,
  'rejectPriceOverride' : ActorMethod<[bigint], undefined>,
  'requestApproval' : ActorMethod<[], undefined>,
  'requestPriceOverride' : ActorMethod<
    [{ 'estimate' : null } | { 'purchase' : null }, number, number],
    bigint
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchTransactions' : ActorMethod<[string], Array<Transaction>>,
  'setApproval' : ActorMethod<[Principal, ApprovalStatus], undefined>,
  'setCompanyBranding' : ActorMethod<
    [string, string, [] | [ExternalBlob]],
    undefined
  >,
  'updateContact' : ActorMethod<
    [
      bigint,
      string,
      string,
      { 'purchaser' : null } |
        { 'billTo' : null },
      { 'wholesaler' : null } |
        { 'retailer' : null },
    ],
    undefined
  >,
  'updateEstimate' : ActorMethod<
    [
      bigint,
      string,
      string,
      Array<EstimateItem>,
      number,
      number,
      boolean,
      number,
      number,
      [] | [Time],
    ],
    undefined
  >,
  'updateProduct' : ActorMethod<[bigint, string, string, number], undefined>,
  'updatePurchase' : ActorMethod<
    [bigint, string, bigint, number, number, string, string, boolean],
    undefined
  >,
  'updateStock' : ActorMethod<[bigint, bigint], undefined>,
  'validatePricing' : ActorMethod<[number, number], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];