/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface PriceOverrideRequest {
    id: bigint;
    status: Variant_pending_approved_rejected;
    referenceId?: bigint;
    sellingPrice: number;
    costPrice: number;
    requestType: Variant_estimate_purchase;
    requestedAt: Time;
    requestedBy: Principal;
}
export type Time = bigint;
export interface Contact {
    id: bigint;
    contactInfo: string;
    contactCategory: Variant_wholesaler_retailer;
    contactType: Variant_purchaser_billTo;
    name: string;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface ProfitAndLoss {
    startTime: Time;
    endTime: Time;
    totalIncome: number;
    totalExpense: number;
    netProfit: number;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface CompanyBranding {
    logo?: ExternalBlob;
    name: string;
    address: string;
}
export interface Transaction {
    id: bigint;
    transactionType: TransactionType;
    date: Time;
    itemOrCustomer: string;
    quantity: bigint;
    price: number;
}
export interface InventoryItem {
    lastUpdated: Time;
    productId: bigint;
    quantity: bigint;
}
export interface UserApprovalInfo {
    status: ApprovalStatus;
    principal: Principal;
}
export interface EstimatePrintData {
    companyBranding?: CompanyBranding;
    estimate: Estimate;
    previousPendingAmount: number;
}
export interface BackupData {
    contacts: Array<[bigint, Contact]>;
    priceOverrideRequests: Array<[bigint, PriceOverrideRequest]>;
    inventory: Array<[bigint, InventoryItem]>;
    companyBranding?: CompanyBranding;
    userProfiles: Array<[Principal, UserProfile]>;
    purchases: Array<[bigint, Purchase]>;
    estimates: Array<[bigint, Estimate]>;
    products: Array<[bigint, Product]>;
}
export interface Estimate {
    id: bigint;
    customerName: string;
    lineItems: Array<EstimateItem>;
    netAmount: number;
    createdAt: Time;
    paymentReceivedTimestamp?: Time;
    isPaid: boolean;
    customerAddress: string;
    totalAmount: number;
    paidAmount: number;
    pendingAmount: number;
}
export interface Purchase {
    id: bigint;
    hasOverride: boolean;
    purchaseDate: Time;
    item: string;
    sellingPrice: number;
    notes: string;
    purchaser: string;
    quantity: bigint;
    costPrice: number;
    profitPercentage: number;
}
export interface EstimateItem {
    rate: number;
    description: string;
    quantity: number;
    amount: number;
}
export interface Product {
    id: bigint;
    stockQuantity: bigint;
    name: string;
    isActive: boolean;
    category: string;
    price: number;
}
export interface UserProfile {
    name: string;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_estimate_purchase {
    estimate = "estimate",
    purchase = "purchase"
}
export enum Variant_pending_approved_rejected {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export enum Variant_purchaser_billTo {
    purchaser = "purchaser",
    billTo = "billTo"
}
export enum Variant_wholesaler_retailer {
    wholesaler = "wholesaler",
    retailer = "retailer"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addContact(name: string, contactInfo: string, contactType: Variant_purchaser_billTo, contactCategory: Variant_wholesaler_retailer): Promise<bigint>;
    addProduct(name: string, category: string, price: number): Promise<bigint>;
    approvePriceOverride(requestId: bigint): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    backupExport(): Promise<BackupData>;
    backupImport(backup: BackupData): Promise<void>;
    createEstimate(customerName: string, customerAddress: string, lineItems: Array<EstimateItem>, totalAmount: number, netAmount: number): Promise<bigint>;
    createPurchase(item: string, quantity: bigint, costPrice: number, sellingPrice: number, purchaser: string, notes: string, hasOverride: boolean): Promise<bigint>;
    deleteContact(contactId: bigint): Promise<void>;
    deleteProduct(productId: bigint): Promise<void>;
    deletePurchase(purchaseId: bigint): Promise<void>;
    generateProfitAndLossReport(startTime: Time, endTime: Time): Promise<ProfitAndLoss>;
    getAllContacts(): Promise<Array<Contact>>;
    getAllEstimates(): Promise<Array<Estimate>>;
    getAllProducts(): Promise<Array<Product>>;
    getAllPurchases(): Promise<Array<Purchase>>;
    getAllTransactions(): Promise<Array<Transaction>>;
    getBillToContacts(): Promise<Array<Contact>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCompanyBranding(): Promise<CompanyBranding | null>;
    getPriceOverrideRequests(): Promise<Array<PriceOverrideRequest>>;
    getPurchaserContacts(): Promise<Array<Contact>>;
    getReportTotals(startTime: Time, endTime: Time): Promise<[number, number]>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    isCallerApproved(): Promise<boolean>;
    isOpenAccess(): Promise<boolean>;
    listApprovals(): Promise<Array<UserApprovalInfo>>;
    markEstimateAsPaid(estimateId: bigint): Promise<void>;
    printEstimate(estimateId: bigint): Promise<EstimatePrintData>;
    recordEstimatePayment(estimateId: bigint, paidAmount: number): Promise<void>;
    rejectPriceOverride(requestId: bigint): Promise<void>;
    requestApproval(): Promise<void>;
    requestPriceOverride(requestType: Variant_estimate_purchase, costPrice: number, sellingPrice: number): Promise<bigint>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    searchTransactions(search: string): Promise<Array<Transaction>>;
    setApproval(user: Principal, status: ApprovalStatus): Promise<void>;
    setCompanyBranding(name: string, address: string, logo: ExternalBlob | null): Promise<void>;
    toggleOpenAccess(value: boolean): Promise<void>;
    updateContact(contactId: bigint, name: string, contactInfo: string, contactType: Variant_purchaser_billTo, contactCategory: Variant_wholesaler_retailer): Promise<void>;
    updateEstimate(estimateId: bigint, customerName: string, customerAddress: string, lineItems: Array<EstimateItem>, totalAmount: number, netAmount: number, isPaid: boolean, pendingAmount: number, paidAmount: number, paymentReceivedTimestamp: Time | null): Promise<void>;
    updateProduct(productId: bigint, name: string, category: string, price: number): Promise<void>;
    updatePurchase(purchaseId: bigint, item: string, quantity: bigint, costPrice: number, sellingPrice: number, purchaser: string, notes: string, hasOverride: boolean): Promise<void>;
    updateStock(productId: bigint, quantity: bigint): Promise<void>;
    validatePricing(costPrice: number, sellingPrice: number): Promise<boolean>;
    validateUser(): Promise<boolean>;
}
import type { ApprovalStatus as _ApprovalStatus, BackupData as _BackupData, CompanyBranding as _CompanyBranding, Contact as _Contact, Estimate as _Estimate, EstimateItem as _EstimateItem, EstimatePrintData as _EstimatePrintData, ExternalBlob as _ExternalBlob, InventoryItem as _InventoryItem, PriceOverrideRequest as _PriceOverrideRequest, Product as _Product, Purchase as _Purchase, Time as _Time, Transaction as _Transaction, TransactionType as _TransactionType, UserApprovalInfo as _UserApprovalInfo, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addContact(arg0: string, arg1: string, arg2: Variant_purchaser_billTo, arg3: Variant_wholesaler_retailer): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addContact(arg0, arg1, to_candid_variant_n8(this._uploadFile, this._downloadFile, arg2), to_candid_variant_n9(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addContact(arg0, arg1, to_candid_variant_n8(this._uploadFile, this._downloadFile, arg2), to_candid_variant_n9(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async addProduct(arg0: string, arg1: string, arg2: number): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addProduct(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addProduct(arg0, arg1, arg2);
            return result;
        }
    }
    async approvePriceOverride(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approvePriceOverride(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approvePriceOverride(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n10(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n10(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async backupExport(): Promise<BackupData> {
        if (this.processError) {
            try {
                const result = await this.actor.backupExport();
                return from_candid_BackupData_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.backupExport();
            return from_candid_BackupData_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async backupImport(arg0: BackupData): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.backupImport(await to_candid_BackupData_n36(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.backupImport(await to_candid_BackupData_n36(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createEstimate(arg0: string, arg1: string, arg2: Array<EstimateItem>, arg3: number, arg4: number): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createEstimate(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createEstimate(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async createPurchase(arg0: string, arg1: bigint, arg2: number, arg3: number, arg4: string, arg5: string, arg6: boolean): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createPurchase(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPurchase(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async deleteContact(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteContact(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteContact(arg0);
            return result;
        }
    }
    async deleteProduct(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProduct(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProduct(arg0);
            return result;
        }
    }
    async deletePurchase(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePurchase(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePurchase(arg0);
            return result;
        }
    }
    async generateProfitAndLossReport(arg0: Time, arg1: Time): Promise<ProfitAndLoss> {
        if (this.processError) {
            try {
                const result = await this.actor.generateProfitAndLossReport(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateProfitAndLossReport(arg0, arg1);
            return result;
        }
    }
    async getAllContacts(): Promise<Array<Contact>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllContacts();
                return from_candid_vec_n55(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllContacts();
            return from_candid_vec_n55(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllEstimates(): Promise<Array<Estimate>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllEstimates();
                return from_candid_vec_n56(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllEstimates();
            return from_candid_vec_n56(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllProducts(): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllProducts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllProducts();
            return result;
        }
    }
    async getAllPurchases(): Promise<Array<Purchase>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPurchases();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPurchases();
            return result;
        }
    }
    async getAllTransactions(): Promise<Array<Transaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTransactions();
                return from_candid_vec_n57(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTransactions();
            return from_candid_vec_n57(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBillToContacts(): Promise<Array<Contact>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBillToContacts();
                return from_candid_vec_n55(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBillToContacts();
            return from_candid_vec_n55(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n61(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n61(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n62(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n62(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCompanyBranding(): Promise<CompanyBranding | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCompanyBranding();
                return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCompanyBranding();
            return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPriceOverrideRequests(): Promise<Array<PriceOverrideRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPriceOverrideRequests();
                return from_candid_vec_n64(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPriceOverrideRequests();
            return from_candid_vec_n64(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPurchaserContacts(): Promise<Array<Contact>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPurchaserContacts();
                return from_candid_vec_n55(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPurchaserContacts();
            return from_candid_vec_n55(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReportTotals(arg0: Time, arg1: Time): Promise<[number, number]> {
        if (this.processError) {
            try {
                const result = await this.actor.getReportTotals(arg0, arg1);
                return [
                    result[0],
                    result[1]
                ];
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReportTotals(arg0, arg1);
            return [
                result[0],
                result[1]
            ];
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n61(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n61(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isCallerApproved(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerApproved();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerApproved();
            return result;
        }
    }
    async isOpenAccess(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isOpenAccess();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isOpenAccess();
            return result;
        }
    }
    async listApprovals(): Promise<Array<UserApprovalInfo>> {
        if (this.processError) {
            try {
                const result = await this.actor.listApprovals();
                return from_candid_vec_n65(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listApprovals();
            return from_candid_vec_n65(this._uploadFile, this._downloadFile, result);
        }
    }
    async markEstimateAsPaid(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markEstimateAsPaid(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markEstimateAsPaid(arg0);
            return result;
        }
    }
    async printEstimate(arg0: bigint): Promise<EstimatePrintData> {
        if (this.processError) {
            try {
                const result = await this.actor.printEstimate(arg0);
                return from_candid_EstimatePrintData_n69(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.printEstimate(arg0);
            return from_candid_EstimatePrintData_n69(this._uploadFile, this._downloadFile, result);
        }
    }
    async recordEstimatePayment(arg0: bigint, arg1: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordEstimatePayment(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordEstimatePayment(arg0, arg1);
            return result;
        }
    }
    async rejectPriceOverride(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectPriceOverride(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectPriceOverride(arg0);
            return result;
        }
    }
    async requestApproval(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.requestApproval();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.requestApproval();
            return result;
        }
    }
    async requestPriceOverride(arg0: Variant_estimate_purchase, arg1: number, arg2: number): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.requestPriceOverride(to_candid_variant_n47(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.requestPriceOverride(to_candid_variant_n47(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async searchTransactions(arg0: string): Promise<Array<Transaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchTransactions(arg0);
                return from_candid_vec_n57(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchTransactions(arg0);
            return from_candid_vec_n57(this._uploadFile, this._downloadFile, result);
        }
    }
    async setApproval(arg0: Principal, arg1: ApprovalStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setApproval(arg0, to_candid_ApprovalStatus_n71(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setApproval(arg0, to_candid_ApprovalStatus_n71(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async setCompanyBranding(arg0: string, arg1: string, arg2: ExternalBlob | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setCompanyBranding(arg0, arg1, await to_candid_opt_n72(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setCompanyBranding(arg0, arg1, await to_candid_opt_n72(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async toggleOpenAccess(arg0: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleOpenAccess(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleOpenAccess(arg0);
            return result;
        }
    }
    async updateContact(arg0: bigint, arg1: string, arg2: string, arg3: Variant_purchaser_billTo, arg4: Variant_wholesaler_retailer): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateContact(arg0, arg1, arg2, to_candid_variant_n8(this._uploadFile, this._downloadFile, arg3), to_candid_variant_n9(this._uploadFile, this._downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateContact(arg0, arg1, arg2, to_candid_variant_n8(this._uploadFile, this._downloadFile, arg3), to_candid_variant_n9(this._uploadFile, this._downloadFile, arg4));
            return result;
        }
    }
    async updateEstimate(arg0: bigint, arg1: string, arg2: string, arg3: Array<EstimateItem>, arg4: number, arg5: number, arg6: boolean, arg7: number, arg8: number, arg9: Time | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateEstimate(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, to_candid_opt_n73(this._uploadFile, this._downloadFile, arg9));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateEstimate(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, to_candid_opt_n73(this._uploadFile, this._downloadFile, arg9));
            return result;
        }
    }
    async updateProduct(arg0: bigint, arg1: string, arg2: string, arg3: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProduct(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProduct(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async updatePurchase(arg0: bigint, arg1: string, arg2: bigint, arg3: number, arg4: number, arg5: string, arg6: string, arg7: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePurchase(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePurchase(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
            return result;
        }
    }
    async updateStock(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateStock(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateStock(arg0, arg1);
            return result;
        }
    }
    async validatePricing(arg0: number, arg1: number): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.validatePricing(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.validatePricing(arg0, arg1);
            return result;
        }
    }
    async validateUser(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.validateUser();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.validateUser();
            return result;
        }
    }
}
function from_candid_ApprovalStatus_n68(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ApprovalStatus): ApprovalStatus {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
async function from_candid_BackupData_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BackupData): Promise<BackupData> {
    return await from_candid_record_n13(_uploadFile, _downloadFile, value);
}
async function from_candid_CompanyBranding_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CompanyBranding): Promise<CompanyBranding> {
    return await from_candid_record_n28(_uploadFile, _downloadFile, value);
}
function from_candid_Contact_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Contact): Contact {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
async function from_candid_EstimatePrintData_n69(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EstimatePrintData): Promise<EstimatePrintData> {
    return await from_candid_record_n70(_uploadFile, _downloadFile, value);
}
function from_candid_Estimate_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Estimate): Estimate {
    return from_candid_record_n34(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_PriceOverrideRequest_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PriceOverrideRequest): PriceOverrideRequest {
    return from_candid_record_n23(_uploadFile, _downloadFile, value);
}
function from_candid_TransactionType_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TransactionType): TransactionType {
    return from_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function from_candid_Transaction_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Transaction): Transaction {
    return from_candid_record_n59(_uploadFile, _downloadFile, value);
}
function from_candid_UserApprovalInfo_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserApprovalInfo): UserApprovalInfo {
    return from_candid_record_n67(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n63(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
async function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CompanyBranding]): Promise<CompanyBranding | null> {
    return value.length === 0 ? null : await from_candid_CompanyBranding_n27(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n30(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    contacts: Array<[bigint, _Contact]>;
    priceOverrideRequests: Array<[bigint, _PriceOverrideRequest]>;
    inventory: Array<[bigint, _InventoryItem]>;
    companyBranding: [] | [_CompanyBranding];
    userProfiles: Array<[Principal, _UserProfile]>;
    purchases: Array<[bigint, _Purchase]>;
    estimates: Array<[bigint, _Estimate]>;
    products: Array<[bigint, _Product]>;
}): Promise<{
    contacts: Array<[bigint, Contact]>;
    priceOverrideRequests: Array<[bigint, PriceOverrideRequest]>;
    inventory: Array<[bigint, InventoryItem]>;
    companyBranding?: CompanyBranding;
    userProfiles: Array<[Principal, UserProfile]>;
    purchases: Array<[bigint, Purchase]>;
    estimates: Array<[bigint, Estimate]>;
    products: Array<[bigint, Product]>;
}> {
    return {
        contacts: from_candid_vec_n14(_uploadFile, _downloadFile, value.contacts),
        priceOverrideRequests: from_candid_vec_n20(_uploadFile, _downloadFile, value.priceOverrideRequests),
        inventory: value.inventory,
        companyBranding: record_opt_to_undefined(await from_candid_opt_n26(_uploadFile, _downloadFile, value.companyBranding)),
        userProfiles: value.userProfiles,
        purchases: value.purchases,
        estimates: from_candid_vec_n31(_uploadFile, _downloadFile, value.estimates),
        products: value.products
    };
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    contactInfo: string;
    contactCategory: {
        wholesaler: null;
    } | {
        retailer: null;
    };
    contactType: {
        purchaser: null;
    } | {
        billTo: null;
    };
    name: string;
}): {
    id: bigint;
    contactInfo: string;
    contactCategory: Variant_wholesaler_retailer;
    contactType: Variant_purchaser_billTo;
    name: string;
} {
    return {
        id: value.id,
        contactInfo: value.contactInfo,
        contactCategory: from_candid_variant_n18(_uploadFile, _downloadFile, value.contactCategory),
        contactType: from_candid_variant_n19(_uploadFile, _downloadFile, value.contactType),
        name: value.name
    };
}
function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: {
        pending: null;
    } | {
        approved: null;
    } | {
        rejected: null;
    };
    referenceId: [] | [bigint];
    sellingPrice: number;
    costPrice: number;
    requestType: {
        estimate: null;
    } | {
        purchase: null;
    };
    requestedAt: _Time;
    requestedBy: Principal;
}): {
    id: bigint;
    status: Variant_pending_approved_rejected;
    referenceId?: bigint;
    sellingPrice: number;
    costPrice: number;
    requestType: Variant_estimate_purchase;
    requestedAt: Time;
    requestedBy: Principal;
} {
    return {
        id: value.id,
        status: from_candid_variant_n24(_uploadFile, _downloadFile, value.status),
        referenceId: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.referenceId)),
        sellingPrice: value.sellingPrice,
        costPrice: value.costPrice,
        requestType: from_candid_variant_n25(_uploadFile, _downloadFile, value.requestType),
        requestedAt: value.requestedAt,
        requestedBy: value.requestedBy
    };
}
async function from_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    logo: [] | [_ExternalBlob];
    name: string;
    address: string;
}): Promise<{
    logo?: ExternalBlob;
    name: string;
    address: string;
}> {
    return {
        logo: record_opt_to_undefined(await from_candid_opt_n29(_uploadFile, _downloadFile, value.logo)),
        name: value.name,
        address: value.address
    };
}
function from_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    customerName: string;
    lineItems: Array<_EstimateItem>;
    netAmount: number;
    createdAt: _Time;
    paymentReceivedTimestamp: [] | [_Time];
    isPaid: boolean;
    customerAddress: string;
    totalAmount: number;
    paidAmount: number;
    pendingAmount: number;
}): {
    id: bigint;
    customerName: string;
    lineItems: Array<EstimateItem>;
    netAmount: number;
    createdAt: Time;
    paymentReceivedTimestamp?: Time;
    isPaid: boolean;
    customerAddress: string;
    totalAmount: number;
    paidAmount: number;
    pendingAmount: number;
} {
    return {
        id: value.id,
        customerName: value.customerName,
        lineItems: value.lineItems,
        netAmount: value.netAmount,
        createdAt: value.createdAt,
        paymentReceivedTimestamp: record_opt_to_undefined(from_candid_opt_n35(_uploadFile, _downloadFile, value.paymentReceivedTimestamp)),
        isPaid: value.isPaid,
        customerAddress: value.customerAddress,
        totalAmount: value.totalAmount,
        paidAmount: value.paidAmount,
        pendingAmount: value.pendingAmount
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_record_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    transactionType: _TransactionType;
    date: _Time;
    itemOrCustomer: string;
    quantity: bigint;
    price: number;
}): {
    id: bigint;
    transactionType: TransactionType;
    date: Time;
    itemOrCustomer: string;
    quantity: bigint;
    price: number;
} {
    return {
        id: value.id,
        transactionType: from_candid_TransactionType_n60(_uploadFile, _downloadFile, value.transactionType),
        date: value.date,
        itemOrCustomer: value.itemOrCustomer,
        quantity: value.quantity,
        price: value.price
    };
}
function from_candid_record_n67(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _ApprovalStatus;
    principal: Principal;
}): {
    status: ApprovalStatus;
    principal: Principal;
} {
    return {
        status: from_candid_ApprovalStatus_n68(_uploadFile, _downloadFile, value.status),
        principal: value.principal
    };
}
async function from_candid_record_n70(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    companyBranding: [] | [_CompanyBranding];
    estimate: _Estimate;
    previousPendingAmount: number;
}): Promise<{
    companyBranding?: CompanyBranding;
    estimate: Estimate;
    previousPendingAmount: number;
}> {
    return {
        companyBranding: record_opt_to_undefined(await from_candid_opt_n26(_uploadFile, _downloadFile, value.companyBranding)),
        estimate: from_candid_Estimate_n33(_uploadFile, _downloadFile, value.estimate),
        previousPendingAmount: value.previousPendingAmount
    };
}
function from_candid_tuple_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [bigint, _Contact]): [bigint, Contact] {
    return [
        value[0],
        from_candid_Contact_n16(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_tuple_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [bigint, _PriceOverrideRequest]): [bigint, PriceOverrideRequest] {
    return [
        value[0],
        from_candid_PriceOverrideRequest_n22(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_tuple_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [bigint, _Estimate]): [bigint, Estimate] {
    return [
        value[0],
        from_candid_Estimate_n33(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    wholesaler: null;
} | {
    retailer: null;
}): Variant_wholesaler_retailer {
    return "wholesaler" in value ? Variant_wholesaler_retailer.wholesaler : "retailer" in value ? Variant_wholesaler_retailer.retailer : value;
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    purchaser: null;
} | {
    billTo: null;
}): Variant_purchaser_billTo {
    return "purchaser" in value ? Variant_purchaser_billTo.purchaser : "billTo" in value ? Variant_purchaser_billTo.billTo : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): Variant_pending_approved_rejected {
    return "pending" in value ? Variant_pending_approved_rejected.pending : "approved" in value ? Variant_pending_approved_rejected.approved : "rejected" in value ? Variant_pending_approved_rejected.rejected : value;
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    estimate: null;
} | {
    purchase: null;
}): Variant_estimate_purchase {
    return "estimate" in value ? Variant_estimate_purchase.estimate : "purchase" in value ? Variant_estimate_purchase.purchase : value;
}
function from_candid_variant_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[bigint, _Contact]>): Array<[bigint, Contact]> {
    return value.map((x)=>from_candid_tuple_n15(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[bigint, _PriceOverrideRequest]>): Array<[bigint, PriceOverrideRequest]> {
    return value.map((x)=>from_candid_tuple_n21(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[bigint, _Estimate]>): Array<[bigint, Estimate]> {
    return value.map((x)=>from_candid_tuple_n32(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Contact>): Array<Contact> {
    return value.map((x)=>from_candid_Contact_n16(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Estimate>): Array<Estimate> {
    return value.map((x)=>from_candid_Estimate_n33(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Transaction>): Array<Transaction> {
    return value.map((x)=>from_candid_Transaction_n58(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PriceOverrideRequest>): Array<PriceOverrideRequest> {
    return value.map((x)=>from_candid_PriceOverrideRequest_n22(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserApprovalInfo>): Array<UserApprovalInfo> {
    return value.map((x)=>from_candid_UserApprovalInfo_n66(_uploadFile, _downloadFile, x));
}
function to_candid_ApprovalStatus_n71(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApprovalStatus): _ApprovalStatus {
    return to_candid_variant_n46(_uploadFile, _downloadFile, value);
}
async function to_candid_BackupData_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BackupData): Promise<_BackupData> {
    return await to_candid_record_n37(_uploadFile, _downloadFile, value);
}
async function to_candid_CompanyBranding_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CompanyBranding): Promise<_CompanyBranding> {
    return await to_candid_record_n49(_uploadFile, _downloadFile, value);
}
function to_candid_Contact_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Contact): _Contact {
    return to_candid_record_n41(_uploadFile, _downloadFile, value);
}
function to_candid_Estimate_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Estimate): _Estimate {
    return to_candid_record_n54(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_PriceOverrideRequest_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PriceOverrideRequest): _PriceOverrideRequest {
    return to_candid_record_n45(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
async function to_candid_opt_n72(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob | null): Promise<[] | [_ExternalBlob]> {
    return value === null ? candid_none() : candid_some(await to_candid_ExternalBlob_n50(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n73(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Time | null): [] | [_Time] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
async function to_candid_record_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    contacts: Array<[bigint, Contact]>;
    priceOverrideRequests: Array<[bigint, PriceOverrideRequest]>;
    inventory: Array<[bigint, InventoryItem]>;
    companyBranding?: CompanyBranding;
    userProfiles: Array<[Principal, UserProfile]>;
    purchases: Array<[bigint, Purchase]>;
    estimates: Array<[bigint, Estimate]>;
    products: Array<[bigint, Product]>;
}): Promise<{
    contacts: Array<[bigint, _Contact]>;
    priceOverrideRequests: Array<[bigint, _PriceOverrideRequest]>;
    inventory: Array<[bigint, _InventoryItem]>;
    companyBranding: [] | [_CompanyBranding];
    userProfiles: Array<[Principal, _UserProfile]>;
    purchases: Array<[bigint, _Purchase]>;
    estimates: Array<[bigint, _Estimate]>;
    products: Array<[bigint, _Product]>;
}> {
    return {
        contacts: to_candid_vec_n38(_uploadFile, _downloadFile, value.contacts),
        priceOverrideRequests: to_candid_vec_n42(_uploadFile, _downloadFile, value.priceOverrideRequests),
        inventory: value.inventory,
        companyBranding: value.companyBranding ? candid_some(await to_candid_CompanyBranding_n48(_uploadFile, _downloadFile, value.companyBranding)) : candid_none(),
        userProfiles: value.userProfiles,
        purchases: value.purchases,
        estimates: to_candid_vec_n51(_uploadFile, _downloadFile, value.estimates),
        products: value.products
    };
}
function to_candid_record_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    contactInfo: string;
    contactCategory: Variant_wholesaler_retailer;
    contactType: Variant_purchaser_billTo;
    name: string;
}): {
    id: bigint;
    contactInfo: string;
    contactCategory: {
        wholesaler: null;
    } | {
        retailer: null;
    };
    contactType: {
        purchaser: null;
    } | {
        billTo: null;
    };
    name: string;
} {
    return {
        id: value.id,
        contactInfo: value.contactInfo,
        contactCategory: to_candid_variant_n9(_uploadFile, _downloadFile, value.contactCategory),
        contactType: to_candid_variant_n8(_uploadFile, _downloadFile, value.contactType),
        name: value.name
    };
}
function to_candid_record_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: Variant_pending_approved_rejected;
    referenceId?: bigint;
    sellingPrice: number;
    costPrice: number;
    requestType: Variant_estimate_purchase;
    requestedAt: Time;
    requestedBy: Principal;
}): {
    id: bigint;
    status: {
        pending: null;
    } | {
        approved: null;
    } | {
        rejected: null;
    };
    referenceId: [] | [bigint];
    sellingPrice: number;
    costPrice: number;
    requestType: {
        estimate: null;
    } | {
        purchase: null;
    };
    requestedAt: _Time;
    requestedBy: Principal;
} {
    return {
        id: value.id,
        status: to_candid_variant_n46(_uploadFile, _downloadFile, value.status),
        referenceId: value.referenceId ? candid_some(value.referenceId) : candid_none(),
        sellingPrice: value.sellingPrice,
        costPrice: value.costPrice,
        requestType: to_candid_variant_n47(_uploadFile, _downloadFile, value.requestType),
        requestedAt: value.requestedAt,
        requestedBy: value.requestedBy
    };
}
async function to_candid_record_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    logo?: ExternalBlob;
    name: string;
    address: string;
}): Promise<{
    logo: [] | [_ExternalBlob];
    name: string;
    address: string;
}> {
    return {
        logo: value.logo ? candid_some(await to_candid_ExternalBlob_n50(_uploadFile, _downloadFile, value.logo)) : candid_none(),
        name: value.name,
        address: value.address
    };
}
function to_candid_record_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    customerName: string;
    lineItems: Array<EstimateItem>;
    netAmount: number;
    createdAt: Time;
    paymentReceivedTimestamp?: Time;
    isPaid: boolean;
    customerAddress: string;
    totalAmount: number;
    paidAmount: number;
    pendingAmount: number;
}): {
    id: bigint;
    customerName: string;
    lineItems: Array<_EstimateItem>;
    netAmount: number;
    createdAt: _Time;
    paymentReceivedTimestamp: [] | [_Time];
    isPaid: boolean;
    customerAddress: string;
    totalAmount: number;
    paidAmount: number;
    pendingAmount: number;
} {
    return {
        id: value.id,
        customerName: value.customerName,
        lineItems: value.lineItems,
        netAmount: value.netAmount,
        createdAt: value.createdAt,
        paymentReceivedTimestamp: value.paymentReceivedTimestamp ? candid_some(value.paymentReceivedTimestamp) : candid_none(),
        isPaid: value.isPaid,
        customerAddress: value.customerAddress,
        totalAmount: value.totalAmount,
        paidAmount: value.paidAmount,
        pendingAmount: value.pendingAmount
    };
}
function to_candid_tuple_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [bigint, Contact]): [bigint, _Contact] {
    return [
        value[0],
        to_candid_Contact_n40(_uploadFile, _downloadFile, value[1])
    ];
}
function to_candid_tuple_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [bigint, PriceOverrideRequest]): [bigint, _PriceOverrideRequest] {
    return [
        value[0],
        to_candid_PriceOverrideRequest_n44(_uploadFile, _downloadFile, value[1])
    ];
}
function to_candid_tuple_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [bigint, Estimate]): [bigint, _Estimate] {
    return [
        value[0],
        to_candid_Estimate_n53(_uploadFile, _downloadFile, value[1])
    ];
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_pending_approved_rejected): {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
} {
    return value == Variant_pending_approved_rejected.pending ? {
        pending: null
    } : value == Variant_pending_approved_rejected.approved ? {
        approved: null
    } : value == Variant_pending_approved_rejected.rejected ? {
        rejected: null
    } : value;
}
function to_candid_variant_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_estimate_purchase): {
    estimate: null;
} | {
    purchase: null;
} {
    return value == Variant_estimate_purchase.estimate ? {
        estimate: null
    } : value == Variant_estimate_purchase.purchase ? {
        purchase: null
    } : value;
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_purchaser_billTo): {
    purchaser: null;
} | {
    billTo: null;
} {
    return value == Variant_purchaser_billTo.purchaser ? {
        purchaser: null
    } : value == Variant_purchaser_billTo.billTo ? {
        billTo: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_wholesaler_retailer): {
    wholesaler: null;
} | {
    retailer: null;
} {
    return value == Variant_wholesaler_retailer.wholesaler ? {
        wholesaler: null
    } : value == Variant_wholesaler_retailer.retailer ? {
        retailer: null
    } : value;
}
function to_candid_vec_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[bigint, Contact]>): Array<[bigint, _Contact]> {
    return value.map((x)=>to_candid_tuple_n39(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[bigint, PriceOverrideRequest]>): Array<[bigint, _PriceOverrideRequest]> {
    return value.map((x)=>to_candid_tuple_n43(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[bigint, Estimate]>): Array<[bigint, _Estimate]> {
    return value.map((x)=>to_candid_tuple_n52(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
